### ISSUE TITLE
Augmenting Long-term Memory

### ISSUE THREAD

**Issue by kino-ngoo** [kino-ngoo/Instapaper_reading#234]
<b>Augmenting Long-term Memory</b><br>
One day in the mid-1920s, a Moscow newspaper reporter named Solomon Shereshevsky entered the laboratory of the psychologist Alexander Luria. Shereshevsky's boss&hellip;<br>
<br>
January 25, 2021 at 08:32PM<br>
via Instapaper https://ift.tt/2NsopfN

**Comment by kinongo** [comment]
#### Using Anki to thoroughly read a research paper in an unfamiliar field

Here's a few examples of the kind of question I entered into Anki at this stage: “What's the size of a Go board?”; “Who plays first in Go?”; “How many human game positions did AlphaGo learn from?”; “Where did AlphaGo get its training data?”; “What were the names of the two main types of neural network AlphaGo used?”

Rather than spending days on a paper, I'll typically spend 10 to 60 minutes, sometimes longer for very good papers. Here's a few notes on some patterns I've found useful in shallow reading.

**Comment by kinongo** [comment]
#### More patterns of Anki use

1. Make most Anki questions and answers as atomic as possible
2. Anki use is best thought of as a virtuoso skill, to be developed
3. Anki isn't just a tool for memorizing simple facts. It's a tool for understanding almost anything.
4. **Use one big deck**
5. Avoid orphan questions
6. Don't share decks
7. Construct your own decks
8. Cultivate strategies for elaborative encoding / forming rich associations
9. What about memory palaces and similar techniques?
10. 95% of Anki's value comes from 5% of the features
11. The challenges of using Anki to store facts about friends and family
12. Procedural versus declarative memory
13. Getting past “names don't matter”
14. What do you do when you get behind?
15. **Using Anki for APIs, books, videos, seminars, conversations, the web, events, and places**
16. Avoid the yes/no pattern
17. Aren't external memory aids enough?
18. If personal memory systems are so great, why aren't they more widely used?
